alter table FR_PERSONS add
(OWNER VARCHAR2(500) NOT NULL,
 NICKNAME VARCHAR2(500) NOT NULL);

alter table FR_GROUPS add
(OWNER VARCHAR2(500) NOT NULL);

alter table FR_PERSONS_GROUPS add
(OWNER VARCHAR2(500) NOT NULL);

alter table FR_PERSONS_RELATIONS add
(OWNER VARCHAR2(500) NOT NULL);
