-- create tables
create table fr_persons (
    person_id                      number generated by default on null as identity 
                                   constraint fr_persons_person_id_pk primary key,
    full_name                      varchar2(4000 char) not null,
    birthdate                      date,
    country                        varchar2(4000 char),
    city                           varchar2(4000 char),
    phone                          varchar2(4000 char)
)
;

create table fr_groups (
    group_id                       number generated by default on null as identity 
                                   constraint fr_groups_group_id_pk primary key,
    group_name                     varchar2(4000 char) not null
)
;

create table fr_persons_groups (
    id                             number generated by default on null as identity 
                                   constraint fr_persons_groups_id_pk primary key,
    person_id                      number
                                   constraint fr_persons_groups_person_id_fk
                                   references fr_persons on delete cascade not null,
    group_id                       number
                                   constraint fr_persons_groups_group_id_fk
                                   references fr_groups on delete cascade not null
)
;

-- table index
create index fr_persons_groups_i1 on fr_persons_groups (group_id);
create index fr_persons_groups_i72 on fr_persons_groups (person_id);

create table fr_relateion_types (
    relation_id                    number generated by default on null as identity 
                                   constraint fr_relateion_ty_relation_id_pk primary key,
    relation_name                  varchar2(4000 char) not null,
    relation_description           varchar2(4000 char),
    is_master_detail               varchar2(3 char) constraint fr_relateion_is_master_det_ck
                                   check (is_master_detail in ('YES','NO')) not null
)
;

create table fr_persons_relations (
    id                             number generated by default on null as identity 
                                   constraint fr_persons_relatio_id_pk primary key,
    person_id_master               number
                                   constraint fr_persons_re_person_id_mas_fk
                                   references fr_persons on delete cascade not null,
    person_id_detail               number
                                   constraint fr_persons_re_person_id_det_fk
                                   references fr_persons on delete cascade not null,
    relation_id                    number
                                   constraint fr_persons_rela_relation_id_fk
                                   references fr_relateion_types on delete cascade not null
)
;

-- table index
create index fr_persons_relatio_i1 on fr_persons_relations (person_id_detail);
create index fr_persons_relatio_i142 on fr_persons_relations (person_id_master);
create index fr_persons_relatio_i153 on fr_persons_relations (relation_id);

-- load data
 
-- Generated by Quick SQL Sunday March 05, 2023  09:50:45
 
/*
fr_persons 
   person_id number /nn /pk
   full_name vc /nn
   birthdate date
   country vc
   city vc
   phone vc

fr_groups   
   group_id number /nn /pk
   group_name vc /nn 

fr_persons_groups
   person_id number /nn /fk fr_persons
   group_id number /nn /fk fr_groups

fr_relateion_types
   relation_id number /nn /pk 
   relation_name vc /nn 
   relation_description vc
   is_master_detail vc(3) /nn /check yes,no

fr_persons_relations 
   person_id_master number /nn /fk fr_persons 
   person_id_detail number /nn /fk fr_persons
   relation_id number /nn /fk fr_relateion_types

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
