create table fr_contacts_share (
	id 							  	number generated by default on null as identity not null enable, 
	person_id 					number not null enable, 
	share_to			 			varchar2(500) not null enable, 
	constraint 					fr_contacts_share_pk primary key (id)
  using index  enable
);

alter table fr_contacts_share add constraint fr_contacts_share_fk 
foreign key (person_id) references fr_persons (person_id) enable;
