create table fr_follow_list (
	id 							  	number generated by default on null as identity not null enable, 
	person_id 					number not null enable, 
	owner			 				  varchar2(500) not null enable, 
	constraint 					fr_follow_list_pk primary key (id)
  using index  enable
);

alter table fr_follow_list add constraint fr_follow_list_fk 
foreign key (person_id) references fr_persons (person_id) enable;
